FROM debian
ADD debian.list /etc/apt/sources.list.d/
RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p kazo.com/img && \
    chmod -R 754 /var/www/kazo.com/ && \
    useradd Kaz && groupadd Bes && usermod -aG Bes Kaz && \
    chown -R Kaz:Bes /var/www/kazo.com/ && \
    sed -i 's/\/var\/www\/html/\/var\/www\/kazo.com/g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Kaz/g' /etc/nginx/nginx.conf
ADD index.html /var/www/kazo.com/
ADD img.jpg /var/www/kazo.com/img/
CMD ["nginx", "-g", "daemon off;"]